worker_processes 1;

events { worker_connections 1024; }

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile      on;

    server {
        listen       80;
        server_name  localhost 192.168.1.11;

        root   C:/Users/user/OneDrive/Desktop/Nouveau dossier/chariot-elevateur/dist/chariot-elevateur/browser;
        index  index.html;

        # Angular routing — redirect all 404s to index.html
        location / {
            try_files $uri $uri/ /index.html;
        }

        # Proxy API calls to Node backend
        location /api/ {
            proxy_pass http://127.0.0.1:3000/api/;
            proxy_set_header Host $host;
        }
    }
}
